version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: trellix
      POSTGRES_USER: trellix_user
      POSTGRES_PASSWORD: trellix_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trellix_user -d trellix"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://trellix_user:trellix_pass@db:5432/trellix?schema=public
      JWT_ACCESS_SECRET: super-secret-access-key-1234567890123456
      JWT_REFRESH_SECRET: super-secret-refresh-key-6543210987654321
      ACCESS_TOKEN_TTL: 15m
      REFRESH_TOKEN_TTL: 7d
      PORT: 4000
      COOKIE_DOMAIN: localhost
      COOKIE_SECURE: "false"
      COOKIE_SAME_SITE: lax
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api/v1
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres-data:
